# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('img', '__first__'),
        ('expt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.AutoField(verbose_name='ID', primary_key=True, serialize=False, auto_created=True)),
                ('confidence', models.FloatField(default=0.0)),
                ('experiment', models.ForeignKey(to='expt.Experiment', related_name='cells')),
                ('series', models.ForeignKey(to='expt.Series', related_name='cells')),
            ],
        ),
        migrations.CreateModel(
            name='CellInstance',
            fields=[
                ('id', models.AutoField(verbose_name='ID', primary_key=True, serialize=False, auto_created=True)),
                ('confidence', models.FloatField(default=0.0)),
                ('region_condition', models.CharField(max_length=255)),
                ('r', models.IntegerField(default=0)),
                ('c', models.IntegerField(default=0)),
                ('z', models.IntegerField(default=0)),
                ('t', models.IntegerField(default=0)),
                ('vr', models.IntegerField(default=0)),
                ('vc', models.IntegerField(default=0)),
                ('vz', models.IntegerField(default=0)),
                ('AreaShape_Area', models.IntegerField(default=0)),
                ('AreaShape_Compactness', models.FloatField(default=0.0)),
                ('AreaShape_Eccentricity', models.FloatField(default=0.0)),
                ('AreaShape_EulerNumber', models.FloatField(default=0.0)),
                ('AreaShape_Extent', models.FloatField(default=0.0)),
                ('AreaShape_FormFactor', models.FloatField(default=0.0)),
                ('AreaShape_MajorAxisLength', models.FloatField(default=0.0)),
                ('AreaShape_MaximumRadius', models.FloatField(default=0.0)),
                ('AreaShape_MeanRadius', models.FloatField(default=0.0)),
                ('AreaShape_MedianRadius', models.FloatField(default=0.0)),
                ('AreaShape_MinorAxisLength', models.FloatField(default=0.0)),
                ('AreaShape_Orientation', models.FloatField(default=0.0)),
                ('AreaShape_Perimeter', models.FloatField(default=0.0)),
                ('AreaShape_Solidity', models.FloatField(default=0.0)),
                ('Location_Center_X', models.FloatField(default=0.0)),
                ('Location_Center_Y', models.FloatField(default=0.0)),
                ('cell', models.ForeignKey(to='cell.Cell', related_name='instances')),
                ('experiment', models.ForeignKey(to='expt.Experiment', related_name='cell_instances')),
            ],
        ),
        migrations.CreateModel(
            name='CellMask',
            fields=[
                ('id', models.AutoField(verbose_name='ID', primary_key=True, serialize=False, auto_created=True)),
                ('gray_value_id', models.IntegerField(default=0)),
                ('confidence', models.FloatField(default=0.0)),
                ('region_condition', models.CharField(max_length=255)),
                ('r', models.IntegerField(default=0)),
                ('c', models.IntegerField(default=0)),
                ('z', models.IntegerField(default=0)),
                ('t', models.IntegerField(default=0)),
                ('vr', models.IntegerField(default=0)),
                ('vc', models.IntegerField(default=0)),
                ('vz', models.IntegerField(default=0)),
                ('AreaShape_Area', models.IntegerField(default=0)),
                ('AreaShape_Compactness', models.FloatField(default=0.0)),
                ('AreaShape_Eccentricity', models.FloatField(default=0.0)),
                ('AreaShape_EulerNumber', models.FloatField(default=0.0)),
                ('AreaShape_Extent', models.FloatField(default=0.0)),
                ('AreaShape_FormFactor', models.FloatField(default=0.0)),
                ('AreaShape_MajorAxisLength', models.FloatField(default=0.0)),
                ('AreaShape_MaximumRadius', models.FloatField(default=0.0)),
                ('AreaShape_MeanRadius', models.FloatField(default=0.0)),
                ('AreaShape_MedianRadius', models.FloatField(default=0.0)),
                ('AreaShape_MinorAxisLength', models.FloatField(default=0.0)),
                ('AreaShape_Orientation', models.FloatField(default=0.0)),
                ('AreaShape_Perimeter', models.FloatField(default=0.0)),
                ('AreaShape_Solidity', models.FloatField(default=0.0)),
                ('Location_Center_X', models.FloatField(default=0.0)),
                ('Location_Center_Y', models.FloatField(default=0.0)),
                ('cell', models.ForeignKey(to='cell.Cell', related_name='masks')),
                ('cell_instance', models.ForeignKey(to='cell.CellInstance', related_name='masks')),
                ('channel', models.ForeignKey(to='img.MaskChannel', related_name='cell_masks')),
                ('experiment', models.ForeignKey(to='expt.Experiment', related_name='cell_masks')),
            ],
        ),
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id', models.AutoField(verbose_name='ID', primary_key=True, serialize=False, auto_created=True)),
                ('r', models.IntegerField(default=0)),
                ('c', models.IntegerField(default=0)),
                ('z', models.IntegerField(default=0)),
                ('channel', models.ForeignKey(null=True, to='img.Channel', related_name='markers')),
                ('composite', models.ForeignKey(to='img.Composite', related_name='markers')),
                ('experiment', models.ForeignKey(to='expt.Experiment', related_name='markers')),
                ('gon', models.ForeignKey(null=True, to='img.Gon', related_name='markers')),
                ('series', models.ForeignKey(to='expt.Series', related_name='markers')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(verbose_name='ID', primary_key=True, serialize=False, auto_created=True)),
                ('name', models.CharField(max_length=255)),
                ('experiment', models.ForeignKey(to='expt.Experiment', related_name='regions')),
            ],
        ),
        migrations.CreateModel(
            name='RegionInstance',
            fields=[
                ('id', models.AutoField(verbose_name='ID', primary_key=True, serialize=False, auto_created=True)),
                ('mode_gray_value_id', models.IntegerField(default=0)),
                ('experiment', models.ForeignKey(to='expt.Experiment', related_name='region_instances')),
                ('region', models.ForeignKey(to='cell.Region', related_name='instances')),
            ],
        ),
        migrations.CreateModel(
            name='RegionMarker',
            fields=[
                ('id', models.AutoField(verbose_name='ID', primary_key=True, serialize=False, auto_created=True)),
                ('region_track_index', models.IntegerField(default=-1)),
                ('r', models.IntegerField(default=0)),
                ('c', models.IntegerField(default=0)),
                ('channel', models.ForeignKey(to='img.Channel', related_name='region_markers')),
                ('composite', models.ForeignKey(to='img.Composite', related_name='region_markers')),
                ('experiment', models.ForeignKey(to='expt.Experiment', related_name='region_markers')),
                ('gon', models.ForeignKey(null=True, to='img.Gon', related_name='region_markers')),
            ],
        ),
        migrations.CreateModel(
            name='RegionMask',
            fields=[
                ('id', models.AutoField(verbose_name='ID', primary_key=True, serialize=False, auto_created=True)),
                ('gray_value_id', models.IntegerField(default=0)),
                ('area', models.IntegerField(default=0)),
                ('experiment', models.ForeignKey(to='expt.Experiment', related_name='region_masks')),
                ('mask', models.ForeignKey(to='img.Mask', related_name='region_masks')),
                ('region', models.ForeignKey(to='cell.Region', related_name='masks')),
                ('region_instance', models.ForeignKey(to='cell.RegionInstance', related_name='masks')),
                ('series', models.ForeignKey(to='expt.Series', related_name='region_masks')),
            ],
        ),
        migrations.CreateModel(
            name='RegionTrack',
            fields=[
                ('id', models.AutoField(verbose_name='ID', primary_key=True, serialize=False, auto_created=True)),
                ('name', models.CharField(max_length=255)),
                ('channel', models.ForeignKey(to='img.Channel', related_name='region_tracks')),
                ('composite', models.ForeignKey(to='img.Composite', related_name='region_tracks')),
                ('experiment', models.ForeignKey(to='expt.Experiment', related_name='region_tracks')),
                ('series', models.ForeignKey(to='expt.Series', related_name='region_tracks')),
            ],
        ),
        migrations.CreateModel(
            name='RegionTrackInstance',
            fields=[
                ('id', models.AutoField(verbose_name='ID', primary_key=True, serialize=False, auto_created=True)),
                ('t', models.IntegerField(default=0)),
                ('channel', models.ForeignKey(to='img.Channel', related_name='region_track_instances')),
                ('composite', models.ForeignKey(to='img.Composite', related_name='region_track_instances')),
                ('experiment', models.ForeignKey(to='expt.Experiment', related_name='region_track_instances')),
                ('region_track', models.ForeignKey(to='cell.RegionTrack', related_name='instances')),
                ('series', models.ForeignKey(to='expt.Series', related_name='region_track_instances')),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(verbose_name='ID', primary_key=True, serialize=False, auto_created=True)),
                ('track_id', models.IntegerField(default=0)),
                ('channel', models.ForeignKey(to='img.Channel', related_name='tracks')),
                ('composite', models.ForeignKey(to='img.Composite', related_name='tracks')),
                ('experiment', models.ForeignKey(to='expt.Experiment', related_name='tracks')),
                ('series', models.ForeignKey(to='expt.Series', related_name='tracks')),
            ],
        ),
        migrations.CreateModel(
            name='TrackInstance',
            fields=[
                ('id', models.AutoField(verbose_name='ID', primary_key=True, serialize=False, auto_created=True)),
                ('t', models.IntegerField(default=0)),
                ('channel', models.ForeignKey(to='img.Channel', related_name='track_instances')),
                ('composite', models.ForeignKey(to='img.Composite', related_name='track_instances')),
                ('experiment', models.ForeignKey(to='expt.Experiment', related_name='track_instances')),
                ('series', models.ForeignKey(to='expt.Series', related_name='track_instances')),
                ('track', models.ForeignKey(to='cell.Track', related_name='instances')),
            ],
        ),
        migrations.AddField(
            model_name='regionmarker',
            name='region_track',
            field=models.ForeignKey(to='cell.RegionTrack', related_name='markers'),
        ),
        migrations.AddField(
            model_name='regionmarker',
            name='region_track_instance',
            field=models.ForeignKey(to='cell.RegionTrackInstance', related_name='markers'),
        ),
        migrations.AddField(
            model_name='regionmarker',
            name='series',
            field=models.ForeignKey(to='expt.Series', related_name='region_markers'),
        ),
        migrations.AddField(
            model_name='regioninstance',
            name='region_track_instance',
            field=models.OneToOneField(to='cell.RegionTrackInstance', related_name='region_instance'),
        ),
        migrations.AddField(
            model_name='regioninstance',
            name='series',
            field=models.ForeignKey(to='expt.Series', related_name='region_instances'),
        ),
        migrations.AddField(
            model_name='region',
            name='region_track',
            field=models.OneToOneField(to='cell.RegionTrack', related_name='regions'),
        ),
        migrations.AddField(
            model_name='region',
            name='series',
            field=models.ForeignKey(to='expt.Series', related_name='regions'),
        ),
        migrations.AddField(
            model_name='marker',
            name='track',
            field=models.ForeignKey(to='cell.Track', related_name='markers'),
        ),
        migrations.AddField(
            model_name='marker',
            name='track_instance',
            field=models.ForeignKey(to='cell.TrackInstance', related_name='markers'),
        ),
        migrations.AddField(
            model_name='cellmask',
            name='marker',
            field=models.ForeignKey(to='cell.Marker', related_name='cell_masks'),
        ),
        migrations.AddField(
            model_name='cellmask',
            name='mask',
            field=models.ForeignKey(to='img.Mask', related_name='cell_masks'),
        ),
        migrations.AddField(
            model_name='cellmask',
            name='region',
            field=models.ForeignKey(null=True, to='cell.Region', related_name='cell_masks'),
        ),
        migrations.AddField(
            model_name='cellmask',
            name='region_instance',
            field=models.ForeignKey(null=True, to='cell.RegionInstance', related_name='cell_masks'),
        ),
        migrations.AddField(
            model_name='cellmask',
            name='series',
            field=models.ForeignKey(to='expt.Series', related_name='cell_masks'),
        ),
        migrations.AddField(
            model_name='cellinstance',
            name='region',
            field=models.ForeignKey(null=True, to='cell.Region', related_name='cell_instances'),
        ),
        migrations.AddField(
            model_name='cellinstance',
            name='region_instance',
            field=models.ForeignKey(null=True, to='cell.RegionInstance', related_name='cell_instances'),
        ),
        migrations.AddField(
            model_name='cellinstance',
            name='series',
            field=models.ForeignKey(to='expt.Series', related_name='cell_instances'),
        ),
        migrations.AddField(
            model_name='cellinstance',
            name='track_instance',
            field=models.OneToOneField(to='cell.TrackInstance', related_name='cell_instance'),
        ),
        migrations.AddField(
            model_name='cell',
            name='track',
            field=models.OneToOneField(to='cell.Track', related_name='cell'),
        ),
    ]
